### ISSUE TITLE
Could You Share the COCO JSON File for SynthTree43k?

### ISSUE THREAD

**Issue by leserein17** [rcondat/convexmask#1]
I hope this message finds you well.
I am currently working on a project related to your work on SynthTree43k and am very interested in replicating your results. I was wondering if you could share the COCO format JSON file for SynthTree43k. It would be incredibly helpful for my project.
Thank you very much for your time and assistance!

**Comment by rcondat** [comment]
The JSON files used for my work are those provided by the SynthTree43k dataset on the following Github repository: https://github.com/norlab-ulaval/PercepTreeV1. These are the whole-tree labeling files (train_RGB_entire_tree.json, val_RGB_entire_tree.json and test_RGB_entire_tree.json).

**Comment by leserein17** [comment]
Oh, thank you for your invaluable assistance and support.
